name: Check, Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Formatting Check
      run: ./gradlew spotlessCheck
    - name: Tests
      run: ./gradlew check
    - name: Build Jar
      run: ./gradlew shadowJar
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: jar
          path: build/libs/emailconverter-*-all.jar
